### PR TITLE
Added support for AUR when building from Arch Linux

### PR DESCRIPTION
**Pull request by leoamaro01**

### CODE REVIEW

**Comment by Apacelus** [comment]
Looks good to me, thx for the help!

**Comment by Apacelus** [comment]
@leoamaro01
```
==> ERROR: Running makepkg as root is not allowed as it can cause permanent, catastrophic damage to your system.
```

**Comment by leoamaro01** [comment]
Yes, I noticed that too, there is no way around that error, revert my commit or simply delete my lines and uncomment the "Install Manually" message

**Comment by WeirdTreeThing** [comment]
You could make a temp user for makepkg and delete it when you are done.

**Comment by leoamaro01** [comment]
No idea really, if you know how be my guest, I don't have that much experience with Arch nor advanced Linux stuff

**Pull request merged**
